version: 2
multi-ecosystem-groups:
  tauri:
    schedule:
      interval: weekly
  tauri-plugin-autostart:
    schedule:
      interval: weekly
  tauri-plugin-notification:
    schedule:
      interval: weekly
  tauri-plugin-opener:
    schedule:
      interval: weekly
  tauri-plugin-shell:
    schedule:
      interval: weekly

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "@tauri-apps/api"
      - dependency-name: "@tauri-apps/plugin-autostart"
      - dependency-name: "@tauri-apps/plugin-notification"
      - dependency-name: "@tauri-apps/plugin-opener"
      - dependency-name: "@tauri-apps/plugin-shell"
    groups:
      vite:
        patterns:
          - vite
          - vitest
          - happy-dom
        update-types:
          - minor
          - patch

  - package-ecosystem: cargo
    directory: /src-tauri
    schedule:
      interval: weekly
    ignore:
      - dependency-name: tauri
      - dependency-name: tauri-plugin-notification
      - dependency-name: tauri-plugin-opener
      - dependency-name: tauri-plugin-shell
      - dependency-name: tauri-plugin-autostart
    groups:
      macos-bindings:
        patterns:
          - "objc2*"
        update-types:
          - minor
          - patch
      windows:
        patterns:
          - "windows*"
          - tauri-winrt-notification
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /
    patterns:
      - "@tauri-apps/api"
    multi-ecosystem-group: tauri

  - package-ecosystem: cargo
    directory: /src-tauri
    patterns:
      - tauri
    multi-ecosystem-group: tauri

  - package-ecosystem: npm
    directory: /
    patterns:
      - "@tauri-apps/plugin-autostart"
    multi-ecosystem-group: tauri-plugin-autostart

  - package-ecosystem: cargo
    directory: /src-tauri
    patterns:
      - tauri-plugin-autostart
    multi-ecosystem-group: tauri-plugin-autostart

  - package-ecosystem: npm
    directory: /
    patterns:
      - "@tauri-apps/plugin-notification"
    multi-ecosystem-group: tauri-plugin-notification

  - package-ecosystem: cargo
    directory: /src-tauri
    patterns:
      - tauri-plugin-notification
    multi-ecosystem-group: tauri-plugin-notification

  - package-ecosystem: npm
    directory: /
    patterns:
      - "@tauri-apps/plugin-opener"
    multi-ecosystem-group: tauri-plugin-opener

  - package-ecosystem: cargo
    directory: /src-tauri
    patterns:
      - tauri-plugin-opener
    multi-ecosystem-group: tauri-plugin-opener

  - package-ecosystem: npm
    directory: /
    patterns:
      - "@tauri-apps/plugin-shell"
    multi-ecosystem-group: tauri-plugin-shell

  - package-ecosystem: cargo
    directory: /src-tauri
    patterns:
      - tauri-plugin-shell
    multi-ecosystem-group: tauri-plugin-shell
