version: 2
multi-ecosystem-groups:
  tauri:
    schedule:
      interval: weekly

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "@tauri-apps/*"
    groups:
      vite:
        patterns:
          - vite
          - vitest
          - happy-dom
        update-types:
          - minor
          - patch

  - package-ecosystem: cargo
    directory: /src-tauri
    schedule:
      interval: weekly
    ignore:
      - dependency-name: tauri
      - dependency-name: tauri-build
      - dependency-name: "tauri-plugin-*"
    groups:
      macos-bindings:
        patterns:
          - "objc2*"
        update-types:
          - minor
          - patch
      windows:
        patterns:
          - "windows*"
          - tauri-winrt-notification
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /
    patterns:
      - "@tauri-apps/*"
    multi-ecosystem-group: tauri

  - package-ecosystem: cargo
    directory: /src-tauri
    patterns:
      - tauri
      - tauri-build
      - "tauri-plugin-*"
    multi-ecosystem-group: tauri
